server:
	logfile: "nsd.log"
	xfrdfile: xfrd.state
	zonesdir: ""
	username: ""
	chroot: ""
	pidfile: nsd.pid
	verbosity: 5
	drop-unauthoritative: NSD_DROP_UNAUTHORITATIVE
	zonelistfile: "zone.list"

zone:
	name: EXAMPLE.NET
	zonefile: drop_unauthoritative.zone
